### ISSUE TITLE
Start Quizz

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#1]
**Value Preposition**
As a User i need an starting point in the Quizz to be able to start the Quizz 

**Acceptance Criteria**

- [x] Functioning Landing Page

- [x] Functioning start Quizz Button

**Description**

<img width="250" alt="Lading Page" src="https://user-images.githubusercontent.com/98757857/159926678-2291e82c-1454-4b8f-9347-4bc13297cb18.png">

**Task**

- [x] create landing page

- [x] create start Quizz Button

- [x] implement function to the button so it navigates the user to the first quizz page
