### ISSUE TITLE
Meat-Quizz-Page

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#12]
**Value Preposition**
As a User i need a quizz site that suggests different types of meat so i can choose my selected meat

**Acceptance Criteria**

- [x] Functioning Meat Quizz Page

- [x] Functioning Buttons

- [x] Added Information to the Buttons so the User can choose their meat type

- [x] functioning quizz counter

**Description**

![meat-quizz-page](https://user-images.githubusercontent.com/98757857/161028375-77cc088a-55c8-4792-9230-bbb80e251fa0.png)

**Task**

- [x] create Meat Quizz Page

- [x] create Buttons

- [x] add information to the Buttons (e.g. Hähnchen, Ente, Schwein, Lamm, Rind)

- [x] implement function to the buttons so it navigates the user to the next quizz page

- [x] implement function to the counter so it decreases by 1 after the user selected their meat type
