### ISSUE TITLE
Wine-Quiz-Page

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#14]
**Value Preposition**
As a User i need a quizz site that suggests different types of wine so i can choose my taste preference

**Acceptance Criteria**

- [x] Functioning Wine Quiz Page

- [x] Functioning Buttons

- [x] Added Information to the Buttons so the User can choose their wine type

- [x] functioning quizz counter

**Description**
![wine quiz page](https://user-images.githubusercontent.com/98757857/161501861-fe72e258-52f8-4d86-99dd-bb3579ec48c7.png)

**Task**

- [x] create Wine Quiz Page

- [x] create Buttons

- [x] add information to the Buttons (e.g. Süß, Trocken)

- [x] add Quiz counter

- [x] implement function to the app so it suggest the user a wine, based on their answers.

- [x] implement function to the buttons so it navigates the user to the result page
