### ISSUE TITLE
First Quizz Page

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#2]
**Value Preposition**
As a user i need an question to my dish and a option to answer the quizz

**Acceptance Criteria**

- [x] Give the User a question to their selected 
        dish

- [x] Give the User a option to answer the 
       question and highlight the answer so the 
       user knows that he selected a dish

- [x] The counter needs to decrease by one with each answerd question

**Description**

<img width="164" alt="Dish options" src="https://user-images.githubusercontent.com/98757857/159932230-f6d3993f-28a5-4957-aa08-12ffcfe22ebd.png">

**Task**

- [x] Add "Was möchtest du Essen?" as an specific Question for the User 

- [x]  Add Buttons to the first Quizz Page

- [x] Fill the Buttons with specific answers to the question for the User

- [x] Add a effect to the button as soon a it is 
       selected by the user
