### ISSUE TITLE
Saving Purchased Wine

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#20]
**Value Preposition**
As a user i need an option to save a Wine to be able to know what wine i bought and the amount i have bought or left.

**Acceptance Criteria**

- [x] Give the User a page to add a selected wine that he bought
- [x] Give the User a button to add a selected wine  to the "Dein Weinkeller" Page
- [x] Give the User a button to increase or decrease the amount of Wine in the "Dein Weinkeller" Page

**Description**

![Dein Weinkeller](https://user-images.githubusercontent.com/98757857/164186704-1abb81b8-1d3a-4af9-91cf-6d72a25d6b41.png)

**Task**

- [x]  Add  "Dein Weinkeller" Page
- [x] Add a wine card to the "Dein Weinkeller "Page.
- [x] Fill the wine card with the wine picture and name
- [x] Add buttons to the wine card so the User can increase or decrease the amount of wine he has.
