### ISSUE TITLE
Quizz counter

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#3]
**Value Preposition**
As a User i need a visual representation of my progress in the Quizz app to be able to know when i get my selected wine options

**Acceptance Criteria**

- [x] the user needs a counter ( numbers ) 
      that show the left questions of the quizz 

**Description**

<img width="244" alt="counter" src="https://user-images.githubusercontent.com/98757857/159933016-0406ad51-b0df-4a71-946e-4a79b8197274.png">

**Task**

- [x] add a div with a information of the left 
       questions

- [x] implement function to the div and the 
      information so that the counter decreases 
      by 1 when the question is answerd
