### ISSUE TITLE
Wine selection

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#4]
**Value Preposition**
As a User i need a wine option after the quiz is answerd to be able to select a Wine.

**Acceptance Criteria**

- [x] the user needs a site on the app that will show him a selected wine, based on his answers that he can choose after he answerd all the questions from the quiz.

**Description**
![Deine Wein Empfehlung](https://user-images.githubusercontent.com/98757857/161224619-ec095902-e73c-4b4a-90b3-7c2a52b1e86a.png)

**Task**

- [x] create a datebase of wine´s

- [x] add a site "Deine Empfehlung" to the app that will show after the user finished the quiz

- [x] implement function to the app so that it will generate a wine that is based on the selceted answers of the user
