### ISSUE TITLE
Wine Information

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#5]
**Value Preposition**
As a User i need important informations about a Wine to be able to buy it and to learn more about the difference of the wines and their own taste.

**Acceptance Criteria**

- [x] the user needs the name of the Wine
- [x] the user needs the type of the Wine
- [x] the user needs the Flavor profile of the Wine
- [x] the user needs a Picture of the Wine
- [x] the user needs information of the fitting dish to the Wine

**Description**
<img width="286" alt="Wein Info FIGMA beispiel" src="https://user-images.githubusercontent.com/98757857/161230293-8098ab0c-eb0f-4026-87b8-c5f30bc5dbde.png">

**Task**

- [x] create a card component
- [x] add it to the "Deine Empfehlung" tab
- [x] add a Picture of the Wine to the card 
        component
- [x] add information of the Wine to the card 
        component
