### ISSUE TITLE
Going Back function

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#6]
**Value Preposition**
As a User i need  an option to move back in 
the quizz to be able to change a falsely selected answer.

**Acceptance Criteria**

- [x] the user needs an button to move back 
        in the app to switch a selected answer

- [x] the user needs to easly understand its 
       function

**Task**

- [x] create a button and add it to each quizz 
        page
- [x] add a back arrow to the button
- [x] implement function to the button so it 
       moves a site back in the quizz app
