### ISSUE TITLE
Navigation between the quizz cards

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#7]
**Value Preposition**
As a User i need an option to enter the next quizz page after i answerd a question to be able to answer a new Question.

**Acceptance Criteria**

- [x] the user needs to be directed to the next quizz page after a click on an answer button.

**Task**

- [x] implement function to the answer button so that the app opens a new quizz page and the user gets a new quizz card

- [x] implement the function to each quizz card
