### ISSUE TITLE
Restart the quizz

### ISSUE THREAD

**Issue by Apollon-Kelenc** [Apollon-Kelenc/capstone-project#8]
**Value Preposition**
As a user i need an option to restart the quizz to be able to get a new selected wine.

**Acceptance Criteria**

- [x] Give the User a button to restart the quizz
- [x] add info in the button so the user knows the function of the button

**Description**

![neue suche bsp](https://user-images.githubusercontent.com/98757857/160369706-06b84521-c2d6-499c-a472-664354edeadd.png)

**Task**

- [x]  Add Button to the "Deine Empfehlung Page"

- [x] Fill the Button with the info " Neue Suche" for the User
- [x] Add a icon to the button
- [x] implement navigation to the beginning of the 
       quizz after the user selected the "Neue Suche" button.
